# Generated by Django 3.2.7 on 2021-09-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
