# Generated by Django 3.2.7 on 2021-09-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_profile_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='posts',
        ),
    ]
